# Generated by Django 5.1.1 on 2024-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_blog_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
