# Generated by Django 5.1.1 on 2024-09-15 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
